/** Preset endpoints for 系统配置 → API 调试 */

export type DebugEndpoint = {
  id: string;
  group: string;
  label: string;
  method: 'GET' | 'POST';
  path: string;
  query?: Record<string, string>;
  body?: string;
};

export const ADMIN_DEBUG_ENDPOINTS: DebugEndpoint[] = [
  { id: 'public', group: 'Admin Public', label: '探活', method: 'GET', path: '/admin/public' },
  {
    id: 'login',
    group: 'Admin Public',
    label: '登录（需 JSON body）',
    method: 'POST',
    path: '/admin/login',
    body: JSON.stringify({ username: '', password: '' }, null, 2),
  },
  { id: 'logout', group: 'Admin Public', label: '退出', method: 'POST', path: '/admin/logout', body: '{}' },
  { id: 'profile', group: 'Admin Account', label: '当前管理员资料', method: 'GET', path: '/admin/account/profile' },
  { id: 'menus', group: 'Admin Account', label: '菜单', method: 'GET', path: '/admin/account/menus' },
  { id: 'permissions', group: 'Admin Account', label: '权限', method: 'GET', path: '/admin/account/permissions' },
  {
    id: 'admin-user-list',
    group: 'Admin User',
    label: '管理员列表',
    method: 'GET',
    path: '/admin/admin-user/list',
    query: { page: '1', page_size: '10', keyword: '' },
  },
  {
    id: 'admin-user-detail',
    group: 'Admin User',
    label: '管理员详情',
    method: 'GET',
    path: '/admin/admin-user/detail',
    query: { id: '1' },
  },
  {
    id: 'admin-user-save',
    group: 'Admin User',
    label: '新增/编辑管理员',
    method: 'POST',
    path: '/admin/admin-user/save',
    body: JSON.stringify(
      {
        id: 0,
        username: '',
        password: '',
        nickname: '',
        avatar: '',
        mobile: '',
        email: '',
        status: 1,
        role_ids: [0],
      },
      null,
      2
    ),
  },
  {
    id: 'admin-user-status',
    group: 'Admin User',
    label: '更新管理员状态',
    method: 'POST',
    path: '/admin/admin-user/status',
    body: JSON.stringify({ id: 0, status: 0 }, null, 2),
  },
  {
    id: 'admin-user-delete',
    group: 'Admin User',
    label: '删除管理员',
    method: 'POST',
    path: '/admin/admin-user/delete',
    body: JSON.stringify({ id: 0 }, null, 2),
  },
  {
    id: 'role-list',
    group: 'Admin Role',
    label: '角色列表',
    method: 'GET',
    path: '/admin/role/list',
    query: { page: '1', page_size: '10', keyword: '' },
  },
  { id: 'role-options', group: 'Admin Role', label: '角色下拉选项', method: 'GET', path: '/admin/role/options' },
  {
    id: 'role-resource-ids',
    group: 'Admin Role',
    label: '角色已绑定资源 ID',
    method: 'GET',
    path: '/admin/role/resource-ids',
    query: { role_id: '1' },
  },
  {
    id: 'role-save',
    group: 'Admin Role',
    label: '新增/编辑角色',
    method: 'POST',
    path: '/admin/role/save',
    body: JSON.stringify(
      { id: 0, name: '', code: '', description: '', sort: 0, status: 1, resource_ids: [0] },
      null,
      2
    ),
  },
  {
    id: 'role-status',
    group: 'Admin Role',
    label: '更新角色状态',
    method: 'POST',
    path: '/admin/role/status',
    body: JSON.stringify({ id: 0, status: 0 }, null, 2),
  },
  {
    id: 'role-delete',
    group: 'Admin Role',
    label: '删除角色',
    method: 'POST',
    path: '/admin/role/delete',
    body: JSON.stringify({ id: 0 }, null, 2),
  },
  {
    id: 'resource-list',
    group: 'Admin Resource',
    label: '资源列表',
    method: 'GET',
    path: '/admin/resource/list',
    query: { type: 'menu', status: '1', parent_id: '', keyword: '' },
  },
  {
    id: 'resource-tree',
    group: 'Admin Resource',
    label: '资源树',
    method: 'GET',
    path: '/admin/resource/tree',
    query: { type: '', status: '1' },
  },
  {
    id: 'resource-save',
    group: 'Admin Resource',
    label: '新增/编辑资源',
    method: 'POST',
    path: '/admin/resource/save',
    body: JSON.stringify(
      {
        id: 0,
        parent_id: 0,
        type: '',
        name: '',
        title: '',
        code: '',
        route_path: '',
        component: '',
        redirect: '',
        icon: '',
        api_method: '',
        api_path: '',
        sort: 0,
        hidden: 0,
        keep_alive: 0,
        status: 1,
        remark: '',
      },
      null,
      2
    ),
  },
  {
    id: 'resource-status',
    group: 'Admin Resource',
    label: '更新资源状态',
    method: 'POST',
    path: '/admin/resource/status',
    body: JSON.stringify({ id: 0, status: 0 }, null, 2),
  },
  {
    id: 'resource-delete',
    group: 'Admin Resource',
    label: '删除资源',
    method: 'POST',
    path: '/admin/resource/delete',
    body: JSON.stringify({ id: 0 }, null, 2),
  },
  {
    id: 'tx-list',
    group: 'Admin Transaction',
    label: '交易列表',
    method: 'GET',
    path: '/admin/transaction/list',
    query: {
      page: '1',
      page_size: '10',
      user_id: '',
      party_id: '',
      keyword: '',
      transaction_type: '',
      transaction_subtype_choice: '',
      start_time: '',
      end_time: '',
      include_raw: '0',
    },
  },
  {
    id: 'tx-overview',
    group: 'Admin Transaction',
    label: '统计概览',
    method: 'GET',
    path: '/admin/transaction/stats/overview',
    query: { days: '7', latest_limit: '10' },
  },
  {
    id: 'tx-trend',
    group: 'Admin Transaction',
    label: '交易趋势',
    method: 'GET',
    path: '/admin/transaction/stats/trend',
    query: { days: '7' },
  },
  {
    id: 'tx-top-users',
    group: 'Admin Transaction',
    label: '用户排行',
    method: 'GET',
    path: '/admin/transaction/stats/top-users',
    query: { days: '7', limit: '10', sort_by: 'amount' },
  },
  {
    id: 'tx-sync',
    group: 'Admin Transaction',
    label: '手动同步交易',
    method: 'POST',
    path: '/admin/transaction/sync',
    body: JSON.stringify(
      { user_id: 0, page_size: 0, max_pages_per_user: 0, max_users_per_round: 0 },
      null,
      2
    ),
  },
];
